CREATE TABLE IF NOT EXISTS buckets (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    owner_id INTEGER NOT NULL CONSTRAINT fk_user
        REFERENCES users (id)
        ON DELETE CASCADE,
    region VARCHAR(64) NOT NULL,
    versioning_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    public_access BOOLEAN NOT NULL DEFAULT FALSE,
    storage_class VARCHAR(64) NOT NULL DEFAULT 'warm',
    encryption_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    total_size BIGINT NOT NULL DEFAULT 0,
    object_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);