name: on push
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26'
    - name: Build
      run: go build -v ./...
    - name: Create .env file
      run: |
        echo "HOST_EMAIL=${{ secrets.HOST_EMAIL }}" >> .env
        echo "PASSWORD_EMAIL=${{ secrets.PASSWORD_EMAIL }}" >> .env
        echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
        echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
        echo "CACHE_LINK=${{ secrets.CACHE_LINK }}" >> .env
        echo "HOST_LINK=${{ secrets.HOST_LINK }}" >> .env
        echo "DB_LINK=${{ secrets.DB_LINK }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "SAFETY_DISK_MARGIN=${{ secrets.SAFETY_DISK_MARGIN }}" >> .env
        echo "MOUNT_PATH=${{ secrets.MOUNT_PATH }}" >> .env
    - name: Test
      run: go test -v ./...
